### ISSUE TITLE
Watch Panel doesn't show its proper information.

### ISSUE THREAD

**Issue by daeyeon** [Samsung/iotjscode#59] opened 2017-11-22 07:31 UTC
Assuming the given code is `var val=0; val++;` and `val` is on the `Watch panel` in debugging status, it shows `val : <not available>`. The lastest iotjs and iotjscode were used. I created a file in iotjscode and sent it to iotjs debug server.

**Comment by knightburton** [comment] 2017-11-22 13:21
Ok, the iotjscode is working properly. The problem is in the JerryScript. The functions of the source code are parsed directly in the JerryScript now, and because of this the `PARSER_LEXICAL_ENV_NEEDED` and the `PARSER_NO_REG_STORE` flags are has to be in the context status flags for executing eval operations by the debugger.

I am gonna be create a PR for this in the Jerry.

**Comment by zherczeg** [comment] 2017-11-22 14:24
https://github.com/jerryscript-project/jerryscript/pull/2119
Needs a jerry update after it is landed (I hope that will not cause another break).

**Comment by knightburton** [comment] 2017-11-22 14:38
The PR is landed, so, I've crated a jerry update PR in the iotjs.
PR: https://github.com/Samsung/iotjs/pull/1322

**Closed** 2017-11-27 09:08 UTC
Labels: bug
